/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fjpogdhneyscekuhuifl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqcG9nZGhuZXlzY2VrdWh1aWZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5NTc2MTEsImV4cCI6MjA3NjUzMzYxMX0.V7-HiPmB9cX3hsAmfYhRDvmWQiw-V5g0G40JDrad518"